[project]
name = 'contracts'
description = 'Prism sBTC Payment Gateway Smart Contracts'
authors = []
telemetry = true
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-token'

[contracts.mock-sbtc-token]
path = 'contracts/mock-sbtc-token.clar'
clarity_version = 3
epoch = 3.1

[contracts.payment-gateway]
path = 'contracts/payment-gateway.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
